[package]
name = "faster-hex"
version = "0.4.1"
authors = ["zhangsoledad <787953403@qq.com>"]
edition = "2018"
keywords = ["simd", "hex"]
license = "MIT"
description = "Fast hex encoding."
repository = "https://github.com/NervosFoundation/faster-hex"
homepage = "https://github.com/NervosFoundation/faster-hex"
readme = "README.md"
exclude = [
    "afl/*",
    "benches/*",
    "fuzz/*"
]


[dev-dependencies]
criterion = "0.3"
rustc-hex = "1.0"
hex = "0.4"
proptest = "0.8"
rand = "0.7.3"

[[bench]]
name = "hex"
harness = false


[[bench]]
name = "check"
harness = false
